### ISSUE TITLE
mac 版本的 app.asar 路径在哪里呢

### ISSUE THREAD

**Issue by N3verL4nd** [SnapdragonLee/TyporaCrack#2]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/11865760/159442250-4eb30be3-1f7d-4e6b-8b0b-e2c7a2980d52.png">

这里并不起作用

**Comment by SnapdragonLee** [comment]
macOS暂时不支持， x86 有可能无法使用。

**Comment by SnapdragonLee** [comment]
本项目基于 Mas0nShi/typoraCracker，因此建议阅读：
https://github.com/Mas0nShi/typoraCracker/issues/22
https://github.com/Mas0nShi/typoraCracker/issues/12
