### ISSUE TITLE
mac支持嘛?

### ISSUE THREAD

**Issue by omaidb** [SnapdragonLee/TyporaCrack#4]
hi,大佬,很高兴发现这个项目,我请请问下您,mac支持嘛?

**Comment by SnapdragonLee** [comment]
emm很抱歉 mac端在这个项目暂时不支持，因为本项目基于typoraCracker。
typoraCracker 本身不支持 MacOS，具体原因建议翻阅：https://github.com/Mas0nShi/typoraCracker/issues/25
当然，如果你是mac端的专业开发人员，我觉得可以自己尝试一下。搜索引擎上新版本的Mac端破解反而要比 Windows/Linux 要多，这里我就不详述了。
