### ISSUE TITLE
How to find the IV and key of AES in v1.2.x

### ISSUE THREAD

**Issue by Jxpro** [SnapdragonLee/TyporaCrack#7]
大佬你好，看到你已经破解v2.x了，可否指明一下新版本的KEY和IV怎么找啊

我看到 [typoraCracker](https://github.com/Mas0nShi/typoraCracker) 的issue里好像有提到key和iv的位置，但是我试了以后还是无法解密

可以分享一下key或者寻找key的方法吗

**Comment by SnapdragonLee** [comment]
typoraCracker中 1.2.x 作者有给出各个版本的 AES iv，你可以查看各个分支。
另外 typoraCracker 的作者已经停止了更新，本仓库很有可能在最近几个版本内因无法解读app.asar而导致项目失败。

**Comment by Jxpro** [comment]
好的，了解，看到了谢谢

**Comment by SnapdragonLee** [comment]
v1.2.4的密钥是自己找的，你可以参考 
https://github.com/Mas0nShi/typoraCracker/issues/39

**Comment by Jxpro** [comment]
好的，我之前是参考了这个issue，但是没注意到新的分支，直接替换了master分支的key和iv，所以代码逻辑不正确导致解密不成功

**Comment by Jxpro** [comment]
感谢指点！！

**Comment by SnapdragonLee** [comment]
欢迎提供新思路
